/**
 * The generated cover page.
 *
 * Two layouts, `cover.layout`: see the TWO LAYOUTS comment in
 * bundletoolCover.js. The tests before the "── Classic layout ──" section run
 * against the FULL fixture, which is pinned to 'grid' explicitly; that section
 * mirrors them against 'classic', the default. Most of what matters in either
 * is "is the right thing on the page, in the right order, on one page" rather
 * than exact coordinates.
 *
 * Rendering the page to text needs pdftotext; those tests skip without it. The
 * ones that do not need it check the layout arithmetic directly, so the module
 * is never completely unexercised.
 *
 * Every fixture here is invented. No client material.
 */
import { test, skip } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import {
  PDFDocument, PDFName, getFontkit,
} from '../public/js/bundletoolPdfLib.js';
import {
  makeCoverPdf, coverTitle, wrapText, layoutCover, flattenCoverConfig,
  PAGE_WIDTH, PAGE_HEIGHT, MARGIN, CONTENT_FLOOR, PREPARED_BY_Y,
} from '../public/js/bundletoolCover.js';
import Config from '../public/js/bundletoolConfig.js';
import { getFontSettings } from '../public/js/bundletoolFontSettings.js';

const FULL = {
  'heading.claimNumber': 'ZC00P00456',
  'cover.matterOf': 'IN THE MATTER OF THE FAMILY LAW ACT 1996',
  'heading.bundleTitle': 'Bundle for hearing on 14 March 2026',
  'heading.projectName': 'Re: X (A Child)',
  'heading.author': 'Example Solicitors',
  'index.fontFace': 'serif',
  'cover.courtName': 'IN THE FAMILY COURT AT CENTRAL LONDON',
  'cover.applicantName': 'MS A SAMPLE',
  'cover.respondentName': 'MR B EXAMPLE',
  // Pinned explicitly: the tests that use FULL check the grid geometry, so
  // they ask for grid whatever the default layout is.
  'cover.layout': 'grid',
};

function havePdftotext() {
  try {
    execFileSync('pdftotext', ['-v'], { stdio: 'ignore' });
    return true;
  } catch { return false; }
}

/** The cover's text, whitespace collapsed, as a reader would search it. */
function coverText(bytes) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'bundletool-cover-'));
  try {
    const file = path.join(dir, 'c.pdf');
    fs.writeFileSync(file, bytes);
    return execFileSync('pdftotext', [file, '-'], { encoding: 'utf8' })
      .replace(/\s+/g, ' ').trim();
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

// ── The title ────────────────────────────────────────────────────────────────

test('the cover title is the bundle title, capitalised, exactly as typed', () => {
  // One title: whatever the bundle is called is what the cover says, with no
  // separate cover title and no hearing date appended to it.
  assert.equal(coverTitle({ 'heading.bundleTitle': 'Bundle for hearing on 14.03.2026' }),
    'BUNDLE FOR HEARING ON 14.03.2026');
});

test('cover title and hearing date fields in stored settings do not reach the cover', () => {
  // Older settings codes and stored bundles may carry them; they are ignored,
  // not appended.
  assert.equal(
    coverTitle({
      'heading.bundleTitle': 'Trial Bundle',
      'cover.hearingInfo': 'PRE-TRIAL REVIEW BUNDLE',
      'cover.hearingDate': '2 May 2026',
    }),
    'TRIAL BUNDLE',
  );
});

test('the title falls back through the bundle title to a bare word', () => {
  // The cover is generated by default, so it has to produce something sensible
  // for a user who has filled nothing in. A blank line between two rules would
  // look like a fault.
  assert.equal(coverTitle({ 'heading.bundleTitle': 'Bundle A' }), 'BUNDLE A');
  assert.equal(coverTitle({}), 'BUNDLE');
});

// ── Wrapping ─────────────────────────────────────────────────────────────────

test('wrapping breaks on words and keeps every one of them', async () => {
  const doc = await PDFDocument.create();
  doc.registerFontkit(await getFontkit());
  const font = await doc.embedFont(
    await fetch(getFontSettings('serif').regular.url).then((r) => r.arrayBuffer()),
  );
  const value = 'MS ALEXANDRA BEATRICE CHARLOTTE DELACROIX-WINTERBOTTOM (formerly known as MS A B C DELACROIX)';
  const lines = wrapText(value, font, 10, PAGE_WIDTH - 2 * MARGIN);
  assert.ok(lines.length > 1, 'a name this long must wrap');
  assert.equal(lines.join(' '), value, 'wrapping must not lose or reorder a word');
  for (const line of lines) {
    assert.ok(font.widthOfTextAtSize(line, 10) <= PAGE_WIDTH - 2 * MARGIN,
      `line overflows the text column: ${line}`);
  }
  assert.deepEqual(wrapText('', font, 10, 400), []);
  assert.deepEqual(wrapText(null, font, 10, 400), []);
});

// ── The page ─────────────────────────────────────────────────────────────────

test('the cover is a single A4 page', async () => {
  const doc = await PDFDocument.load(await makeCoverPdf(FULL));
  assert.equal(doc.getPageCount(), 1);
  const { width, height } = doc.getPage(0).getMediaBox();
  assert.ok(Math.abs(width - PAGE_WIDTH) < 0.01 && Math.abs(height - PAGE_HEIGHT) < 0.01);
});

test('every field the cover is given reaches the page', async (t) => {
  if (!havePdftotext()) return skip('pdftotext is needed to read the rendered page');
  const text = coverText(await makeCoverPdf(FULL));

  for (const expected of [
    'IN THE FAMILY COURT AT CENTRAL LONDON',
    'IN THE MATTER OF THE FAMILY LAW ACT 1996',
    'CASE NO: ZC00P00456',
    'MS A SAMPLE',
    'APPLICANT',
    'MR B EXAMPLE',
    'RESPONDENT',
    'BUNDLE FOR HEARING ON 14 MARCH 2026',
    'Prepared by: Example Solicitors',
  ]) {
    assert.ok(text.includes(expected), `the cover does not carry ${JSON.stringify(expected)}: ${text}`);
  }
  // heading.projectName ("Parties") is collected for the PDF's Subject
  // metadata (bundletoolMeta.js) but is not drawn on the page itself: the
  // middle band already names the parties.
  assert.ok(!text.includes('Re: X (A Child)'),
    'the case name is redundant with Applicant/Respondent and must not be drawn twice');

  // ...and in that order: court, case number, matter-of, then the parties,
  // top to bottom; the title and "Prepared by" are pinned to the foot of
  // the page (see GEOMETRY in bundletoolCover.js), so they read LAST on a
  // page this short, same as pdftotext's own top-to-bottom order.
  // pdftotext groups by physical row, not by column: the two names share a
  // row (left then right), then the two labels share the next row (left
  // then right), not name-then-its-own-label the way reading a single
  // column would.
  const order = ['IN THE FAMILY COURT', 'CASE NO', 'IN THE MATTER OF',
    'MS A SAMPLE', 'MR B EXAMPLE', 'APPLICANT', 'RESPONDENT',
    'BUNDLE FOR HEARING ON', 'Prepared by:'];
  let at = -1;
  for (const token of order) {
    const next = text.indexOf(token, at + 1);
    assert.ok(next > at, `${token} is out of order on the cover: ${text}`);
    at = next;
  }
});

test('an empty field leaves its block off the page rather than printing a blank one', async (t) => {
  if (!havePdftotext()) return skip('pdftotext is needed to read the rendered page');
  const text = coverText(await makeCoverPdf({
    'heading.bundleTitle': 'Bundle A',
    'index.fontFace': 'helvetica',
  }));
  assert.ok(!text.includes('Applicant'));
  assert.ok(!text.includes('Respondent'));
  assert.ok(!text.includes('CASE NO'));
  assert.ok(!text.includes('Prepared by'));
  assert.ok(text.includes('BUNDLE A'), 'the title is the one thing that is always drawn');
});

test('one party named on its own does not print a label for the other', async (t) => {
  if (!havePdftotext()) return skip('pdftotext is needed to read the rendered page');
  const text = coverText(await makeCoverPdf({
    ...FULL, 'cover.respondentName': '',
  }));
  assert.ok(text.includes('MS A SAMPLE'));
  assert.ok(text.includes('APPLICANT'));
  assert.ok(!text.includes('RESPONDENT'), 'an unnamed respondent must not get a label to itself');
});

test('up to 4 names a side are drawn, one per line, and a 5th is dropped', async (t) => {
  if (!havePdftotext()) return skip('pdftotext is needed to read the rendered page');
  const text = coverText(await makeCoverPdf({
    ...FULL,
    'cover.applicantName': 'FIRST APPLICANT\nSECOND APPLICANT\nTHIRD APPLICANT\nFOURTH APPLICANT\nFIFTH APPLICANT',
  }));
  for (const name of ['FIRST APPLICANT', 'SECOND APPLICANT', 'THIRD APPLICANT', 'FOURTH APPLICANT']) {
    assert.ok(text.includes(name), `${name} missing from the cover: ${text}`);
  }
  assert.ok(!text.includes('FIFTH APPLICANT'), 'a 5th applicant must be dropped, not just hidden by the UI');
});

test('the case number is always on its own line beneath the court name', async (t) => {
  if (!havePdftotext()) return skip('pdftotext is needed to read the rendered page');
  const text = coverText(await makeCoverPdf({
    ...FULL,
    'cover.courtName': 'IN THE FAMILY COURT AT A VERY LONG COURT NAME INDEED SITTING AT CENTRAL LONDON',
  }));
  // Collapsed to one line by coverText()'s whitespace-collapse, so the real
  // assertion is that the case number is not glued onto the end of the
  // court name with no separator a reader would notice: it is its own
  // "CASE NO:" token, always.
  assert.ok(text.includes('CASE NO: ZC00P00456'), `case number missing or malformed: ${text}`);
});

test('the cover is set in the index font, so the two front pages match', async () => {
  for (const [fontKey, expected] of [['serif', /NotoSerif/i], ['traditional', /Garamond/i], ['monospaced', /Ubuntu/i]]) {
    const doc = await PDFDocument.load(await makeCoverPdf({ ...FULL, 'index.fontFace': fontKey }));
    const names = [];
    for (const [, obj] of doc.context.enumerateIndirectObjects()) {
      const base = obj?.get?.(PDFName.of('BaseFont'));
      if (base) names.push(String(base));
    }
    assert.match(names.join(','), expected, `${fontKey} cover did not embed the expected family`);
  }
});

test('a font key this build does not ship still produces a cover', async () => {
  const doc = await PDFDocument.load(await makeCoverPdf({ ...FULL, 'index.fontFace': 'texgyreheros' }));
  assert.equal(doc.getPageCount(), 1);
});

// ── Fitting ──────────────────────────────────────────────────────────────────

test('long names wrap and the content still clears the page-number footer', async (t) => {
  if (!havePdftotext()) return skip('pdftotext is needed to read the rendered page');
  const long = {
    ...FULL,
    'cover.applicantName': 'MS ALEXANDRA BEATRICE CHARLOTTE DELACROIX-WINTERBOTTOM (formerly known as MS A B C DELACROIX)',
    'cover.respondentName': 'MR BENEDICT CHRISTOPHER DAVIDSON-FITZWILLIAM THE THIRD OF SOMEWHERE VERY LONG INDEED',
    'heading.bundleTitle': 'BUNDLE FOR THE FINAL HEARING OF THE APPLICATION FOR A CHILD ARRANGEMENTS ORDER AND A PROHIBITED STEPS ORDER',
  };
  const doc = await PDFDocument.load(await makeCoverPdf(long));
  assert.equal(doc.getPageCount(), 1, 'the cover must never run to two pages');

  const text = coverText(await makeCoverPdf(long));
  assert.ok(text.includes('DELACROIX-WINTERBOTTOM'), 'a wrapped name must survive wrapping');
  assert.ok(text.includes('PROHIBITED STEPS ORDER'));
});

test('a single very long party name wraps within its own half of the page', async (t) => {
  // The applicant and respondent band is two independent columns of draw()
  // calls, not block() (which always wraps): each name must still wrap,
  // against half the page width instead of the full one.
  if (!havePdftotext()) return skip('pdftotext is needed to read the rendered page');
  const text = coverText(await makeCoverPdf({
    ...FULL,
    'cover.applicantName': 'MS ALEXANDRA BEATRICE CHARLOTTE DELACROIX-WINTERBOTTOM OF SOMEWHERE VERY LONG INDEED INDEED',
  }));
  assert.ok(text.includes('DELACROIX-WINTERBOTTOM'), `a long applicant name did not survive wrapping: ${text}`);
});

test('the gap scaling is what keeps a crowded cover on the page', async () => {
  // The measurement without the drawing: layoutCover() reports where the last
  // flowed line landed. At full gaps the crowded case runs below the floor;
  // makeCoverPdf() is what tries smaller gaps, so prove both halves.
  const doc = await PDFDocument.create();
  doc.registerFontkit(await getFontkit());
  const settings = getFontSettings('serif');
  const fonts = {
    regular: await doc.embedFont(await fetch(settings.regular.url).then((r) => r.arrayBuffer())),
    bold: await doc.embedFont(await fetch(settings.bold.url).then((r) => r.arrayBuffer())),
  };
  // This fixture is deliberately absurd. Ordinary input (even the very long
  // party names in the test above) clears the floor at full gaps with room to
  // spare, which is the intended behaviour: the CLI's spacing is used exactly
  // unless it genuinely cannot be. Reaching the scaling at all takes a single
  // "name" absurd enough to wrap into two dozen-plus lines within its own
  // half-width column, so the fixture is built to have that rather than
  // dressed up as a realistic case it is not.
  const many = (word, n) => Array(n).fill(word).join(' ');
  const crowded = {
    ...FULL,
    'cover.applicantName': many('APPLICANT', 120),
    'cover.respondentName': many('RESPONDENT', 120),
  };
  const atFullGaps = layoutCover(crowded, fonts, 1, null);
  assert.ok(atFullGaps < CONTENT_FLOOR,
    `this fixture is meant to overflow at full gaps but reached ${atFullGaps.toFixed(1)}; `
    + 'so it does not test the scaling');
  assert.ok(layoutCover(crowded, fonts, 0.3, null) > atFullGaps,
    'shrinking the gaps must actually recover vertical space');

  const rendered = await PDFDocument.load(await makeCoverPdf(crowded));
  assert.equal(rendered.getPageCount(), 1);

  // A modest cover must NOT be squeezed: the scaling only fires when needed.
  assert.ok(layoutCover(FULL, fonts, 1, null) >= CONTENT_FLOOR,
    'an ordinary cover should fit at full gaps and keep the CLI spacing exactly');
});

test('"Prepared by" sits clear of the page-number footer zone', () => {
  // The footer plate starts 8pt up and is at most ~47pt tall at the largest
  // footer size, with 4pt of blanking above it. If this line moved down into
  // that band the blanking rectangle would erase it on every bundle.
  assert.ok(PREPARED_BY_Y > 8 + 47 + 4,
    `PREPARED_BY_Y ${PREPARED_BY_Y} is inside the footer's blanking zone`);
  assert.ok(CONTENT_FLOOR > PREPARED_BY_Y,
    'flowed content must stop above the "Prepared by" line, not on top of it');
});

// ── Config plumbing ──────────────────────────────────────────────────────────

test('flattenCoverConfig reads exactly the fields the cover draws', () => {
  const config = new Config();
  config.updateOptions({
    heading: { claimNumber: 'AB-1', bundleTitle: 'T', projectName: 'P', author: 'A' },
    index: { fontFace: 'serif' },
    cover: {
      courtName: 'COURT', matterOf: 'MO', applicantName: 'AP', respondentName: 'RE',
      partyLabel1: 'PL1', partyLabel2: 'PL2',
      extraText: 'ET',
    },
  });
  assert.deepEqual(flattenCoverConfig(config), {
    'heading.claimNumber': 'AB-1',
    'heading.bundleTitle': 'T',
    'heading.projectName': 'P',
    'heading.author': 'A',
    'index.fontFace': 'serif',
    'cover.courtName': 'COURT',
    'cover.matterOf': 'MO',
    'cover.applicantName': 'AP',
    'cover.respondentName': 'RE',
    'cover.partyLabel1': 'PL1',
    'cover.partyLabel2': 'PL2',
    'cover.extraText': 'ET',
    'cover.claimNumber': null,
    'cover.bundleTitle': null,
    'cover.author': null,
    // Which cover geometry is drawn. 'classic' is Config's own default (see
    // TWO LAYOUTS in bundletoolCover.js).
    'cover.layout': 'classic',
    // The cover's placement settings, at their defaults.
    'cover.caseNumberLine': 'court',
    'cover.partyLabelPlacement': 'inline',
    'cover.partyAlign': 'centre',
    'cover.caseNumberAlign': 'right',
    'cover.headingAlign': 'left',
    // The rules above and below the title.
    'cover.titleLines': 'single',
    // The prefix printed before the case number.
    'cover.caseNumberLabel': 'CASE NO:',
    // The label printed before who prepared the bundle.
    'cover.preparedByLabel': 'Prepared by:',
    // The word joining the two parties on the classic design.
    'cover.partyJoiner': '-and-',
    // The cover is drawn at the bundle's page size, so layoutCover needs to
    // know it. A4 is the default.
    'pageOptions.pageSize': 'a4',
  });
});

test('the matter-of line survives the whole live path: Config in, rendered page out', async (t) => {
  // The FULL fixture above hands 'cover.matterOf' to makeCoverPdf() directly,
  // so it cannot see the key go missing on the live path, which goes UI ->
  // Config -> flattenCoverConfig(). This test takes the same road the app
  // takes, so Config and the flatten list must both carry the key.
  if (!havePdftotext()) return skip('pdftotext is needed to read the rendered page');
  const config = new Config();
  config.updateOptions({
    cover: { matterOf: 'IN THE MATTER OF THE CHILDREN ACT 1989' },
  });
  const text = coverText(await makeCoverPdf(flattenCoverConfig(config)));
  assert.ok(text.includes('IN THE MATTER OF THE CHILDREN ACT 1989'),
    `the statute line typed into the form never reached the page: ${text}`);
});

test('a default Config generates no cover, and validates', () => {
  // Covers are opt-in through the coversheet maker: confirming a design there
  // is what sets generateCover. A default of true would draw a cover nobody
  // asked for.
  const config = new Config();
  assert.equal(config.getOption('pageOptions.generateCover'), false,
    'a cover exists only once the user confirms one in the maker');
  config.validateStructure();
  config.validateOptions();
});

test('a default Config draws the classic layout', () => {
  // Classic is the default, and grid an option alongside it: see TWO LAYOUTS
  // in bundletoolCover.js.
  const config = new Config();
  assert.equal(config.getOption('cover.layout'), 'classic',
    'classic must be the default layout, not grid');
});

test('an invalid cover layout is rejected', () => {
  const config = new Config();
  config.updateOptions({ cover: { layout: 'not-a-real-layout' } });
  assert.throws(() => config.validateOptions(), /Invalid cover layout/);
});

// ── Configurable party labels ────────────────────────────────────────────────

test('the party labels are a setting, drawn in caps', async (t) => {
  if (!havePdftotext()) return skip('pdftotext is needed to read the rendered page');
  const text = coverText(await makeCoverPdf({
    ...FULL,
    'cover.partyLabel1': 'Claimant',
    'cover.partyLabel2': 'Defendant',
  }));
  assert.ok(text.includes('CLAIMANT'), `custom first-party label missing: ${text}`);
  assert.ok(text.includes('DEFENDANT'), `custom second-party label missing: ${text}`);
  assert.ok(!text.includes('APPLICANT'), 'the default label must not appear beside a custom one');
  assert.ok(!text.includes('RESPONDENT'), 'the default label must not appear beside a custom one');
});

test('blank party labels fall back to Applicant and Respondent', async (t) => {
  // FULL carries no partyLabel keys at all, as a bundle saved without the
  // setting does.
  if (!havePdftotext()) return skip('pdftotext is needed to read the rendered page');
  const text = coverText(await makeCoverPdf(FULL));
  assert.ok(text.includes('APPLICANT'));
  assert.ok(text.includes('RESPONDENT'));
});

// ── The coversheet editor's free-text block ──────────────────────────────────

test('extra text lines are drawn in order, beneath the title', async (t) => {
  // The grid's title is centred beneath the parties, and the free text flows
  // beneath it, as the coversheet editor's own hint says.
  if (!havePdftotext()) return skip('pdftotext is needed to read the rendered page');
  const text = coverText(await makeCoverPdf({
    ...FULL,
    'cover.extraText': 'Hearing before District Judge Sample\nTime estimate: 2 hours\nApplicant to attend remotely',
  }));
  for (const line of ['Hearing before District Judge Sample', 'Time estimate: 2 hours', 'Applicant to attend remotely']) {
    assert.ok(text.includes(line), `extra line missing from the cover: ${line}`);
  }
  // ...and in the order typed.
  const first = text.indexOf('Hearing before District Judge Sample');
  const second = text.indexOf('Time estimate: 2 hours');
  const third = text.indexOf('Applicant to attend remotely');
  assert.ok(first > -1 && first < second && second < third, `extra text out of order: ${text}`);
  const titleAt = text.indexOf('BUNDLE FOR HEARING ON 14 MARCH 2026');
  assert.ok(titleAt > -1 && titleAt < first, 'the free text belongs beneath the title');
});

test('no extra text means no extra block', async (t) => {
  if (!havePdftotext()) return skip('pdftotext is needed to read the rendered page');
  // The control: FULL carries no extraText and its render must not change.
  const text = coverText(await makeCoverPdf(FULL));
  assert.ok(text.includes('Prepared by: Example Solicitors'));
});

// ── Classic layout (`cover.layout: 'classic'`, the default) ───────────────────
//
// The default layout, with grid as the option alongside it: see TWO LAYOUTS in
// bundletoolCover.js. These mirror the grid tests above against classic's own
// geometry: centred BETWEEN:/-and-, the title ruled above and below, "Prepared
// by" bottom-LEFT (not bottom-right, since there is no bottom-left title box
// competing for the spot). Several lines and several parties a side are handled
// too (see the header of bundletoolCover.js), since the fields are shared
// multi-line textareas.

const CLASSIC = { ...FULL, 'cover.layout': 'classic' };

test('classic: every field the cover is given reaches the page, in order', async (t) => {
  if (!havePdftotext()) return skip('pdftotext is needed to read the rendered page');
  const text = coverText(await makeCoverPdf(CLASSIC));

  for (const expected of [
    'IN THE FAMILY COURT AT CENTRAL LONDON',
    'IN THE MATTER OF THE FAMILY LAW ACT 1996',
    'CASE NO: ZC00P00456',
    'BETWEEN:',
    'MS A SAMPLE',
    'APPLICANT',
    '-and-',
    'MR B EXAMPLE',
    'RESPONDENT',
    'BUNDLE FOR HEARING ON 14 MARCH 2026',
    'Prepared by: Example Solicitors',
  ]) {
    assert.ok(text.includes(expected), `classic cover does not carry ${JSON.stringify(expected)}: ${text}`);
  }
  // No duplicate case name, as on grid (see the header of bundletoolCover.js):
  // classic has its own Applicant/Respondent band, so the case name would be
  // redundant here too.
  assert.ok(!text.includes('Re: X (A Child)'),
    'the case name is redundant with the BETWEEN: block and must not be drawn twice');

  const order = ['IN THE FAMILY COURT', 'CASE NO', 'IN THE MATTER OF', 'BETWEEN:',
    'MS A SAMPLE', 'APPLICANT', '-and-', 'MR B EXAMPLE', 'RESPONDENT',
    'BUNDLE FOR HEARING ON', 'Prepared by:'];
  let at = -1;
  for (const token of order) {
    const next = text.indexOf(token, at + 1);
    assert.ok(next > at, `${token} is out of order on the classic cover: ${text}`);
    at = next;
  }
});

test('classic: an empty field leaves its block off the page rather than printing a blank one', async (t) => {
  if (!havePdftotext()) return skip('pdftotext is needed to read the rendered page');
  const text = coverText(await makeCoverPdf({
    'heading.bundleTitle': 'Bundle A',
    'index.fontFace': 'helvetica',
    'cover.layout': 'classic',
  }));
  assert.ok(!text.includes('BETWEEN'), 'no parties were given, so there is nothing to be between');
  assert.ok(!text.includes('Applicant'));
  assert.ok(!text.includes('Respondent'));
  assert.ok(!text.includes('CASE NO'));
  assert.ok(!text.includes('Prepared by'));
  assert.ok(text.includes('BUNDLE A'), 'the title is the one thing that is always drawn');
});

test('classic: one party named on its own does not join it to a missing other half', async (t) => {
  if (!havePdftotext()) return skip('pdftotext is needed to read the rendered page');
  const text = coverText(await makeCoverPdf({
    ...CLASSIC, 'cover.respondentName': '',
  }));
  assert.ok(text.includes('MS A SAMPLE'));
  assert.ok(text.includes('APPLICANT'));
  assert.ok(!text.includes('RESPONDENT'), 'an unnamed respondent must not get a label to itself');
  assert.ok(!text.includes('-and-'), 'nothing to join, so no "-and-"');
});

test('classic: up to 4 names a side stack centred, one per line, each numbered, and a 5th is dropped', async (t) => {
  // The party fields are multi-line textareas shared with grid, so classic
  // has to cope with more than one name a side too, not just a single
  // centred name.
  if (!havePdftotext()) return skip('pdftotext is needed to read the rendered page');
  const text = coverText(await makeCoverPdf({
    ...CLASSIC,
    'cover.applicantName': 'FIRST APPLICANT\nSECOND APPLICANT\nTHIRD APPLICANT\nFOURTH APPLICANT\nFIFTH APPLICANT',
  }));
  for (const name of ['FIRST APPLICANT', 'SECOND APPLICANT', 'THIRD APPLICANT', 'FOURTH APPLICANT']) {
    assert.ok(text.includes(name), `${name} missing from the classic cover: ${text}`);
  }
  assert.ok(!text.includes('FIFTH APPLICANT'), 'a 5th applicant must be dropped, not just hidden by the UI');
  // With more than one person on a side each is labelled and numbered: 1ST APPLICANT ... 4TH APPLICANT.
  for (const label of ['1ST APPLICANT', '2ND APPLICANT', '3RD APPLICANT', '4TH APPLICANT']) {
    assert.ok(text.includes(label), `${label} missing: ${text}`);
  }
  assert.equal((text.match(/APPLICANT/g) || []).length, 8, 'exactly 4 names plus 4 numbered labels, no more');
});

test('classic: the matter-of block accepts more than one line', async (t) => {
  if (!havePdftotext()) return skip('pdftotext is needed to read the rendered page');
  const text = coverText(await makeCoverPdf({
    ...CLASSIC,
    'cover.matterOf': 'IN THE MATTER OF THE CHILDREN ACT 1989\nRe: X (A Child)',
  }));
  assert.ok(text.includes('IN THE MATTER OF THE CHILDREN ACT 1989'), `first matter-of line missing: ${text}`);
  assert.ok(text.includes('Re: X (A Child)'), `second matter-of line missing: ${text}`);
});

test('classic: extra text is drawn beneath the title, not above it', async (t) => {
  // Classic's title sits mid-page, between the two rules, and the extra text
  // flows beneath it, in the CLI's own order.
  if (!havePdftotext()) return skip('pdftotext is needed to read the rendered page');
  const text = coverText(await makeCoverPdf({
    ...CLASSIC,
    'cover.extraText': 'Hearing before District Judge Sample',
  }));
  const afterTitle = text.indexOf('BUNDLE FOR HEARING ON 14 MARCH 2026');
  assert.ok(afterTitle > -1, `title missing from classic cover: ${text}`);
  assert.ok(text.indexOf('Hearing before District Judge Sample') > afterTitle,
    'the free text belongs below the title in classic, not above it');
});

test('classic: "Prepared by" sits bottom-left, not wrapped, unlike grid\'s bottom-right', async (t) => {
  if (!havePdftotext()) return skip('pdftotext is needed to read the rendered page');
  const text = coverText(await makeCoverPdf(CLASSIC));
  assert.ok(text.includes('Prepared by: Example Solicitors'), `Prepared by missing: ${text}`);
});

test('classic: a crowded cover still clears the page-number footer and stays one page', async () => {
  const doc = await PDFDocument.create();
  doc.registerFontkit(await getFontkit());
  const settings = getFontSettings('serif');
  const fonts = {
    regular: await doc.embedFont(await fetch(settings.regular.url).then((r) => r.arrayBuffer())),
    bold: await doc.embedFont(await fetch(settings.bold.url).then((r) => r.arrayBuffer())),
  };
  const many = (word, n) => Array(n).fill(word).join(' ');
  const crowded = {
    ...CLASSIC,
    'cover.applicantName': many('APPLICANT', 120),
    'cover.respondentName': many('RESPONDENT', 120),
  };
  const atFullGaps = layoutCover(crowded, fonts, 1, null);
  assert.ok(atFullGaps < CONTENT_FLOOR,
    `this fixture is meant to overflow at full gaps but reached ${atFullGaps.toFixed(1)}`);
  assert.ok(layoutCover(crowded, fonts, 0.3, null) > atFullGaps,
    'shrinking the gaps must recover vertical space in classic too');
  const rendered = await PDFDocument.load(await makeCoverPdf(crowded));
  assert.equal(rendered.getPageCount(), 1, 'a crowded classic cover must never run to two pages');
});


// ── Court Ref/Claim No., Bundle Title and Prepared By follow Basic Information until the
// coversheet overrides them ────────────────────────────────────────────────────────

test('the cover follows Basic Information when it has no title of its own', () => {
  const cv = { 'heading.bundleTitle': 'Basic Info Title', 'cover.bundleTitle': null };
  assert.equal(coverTitle(cv), 'BASIC INFO TITLE');
  assert.equal(coverTitle({ 'heading.bundleTitle': 'Basic Info Title' }), 'BASIC INFO TITLE', 'undefined follows too');
});

test('a title set on the coversheet wins over Basic Information, and changing Basic Information later does not move it', () => {
  const cv = { 'heading.bundleTitle': 'Basic Info Title', 'cover.bundleTitle': 'Cover Only Title' };
  assert.equal(coverTitle(cv), 'COVER ONLY TITLE');
  assert.equal(coverTitle({ ...cv, 'heading.bundleTitle': 'Changed In Step 1' }), 'COVER ONLY TITLE');
});

test('an empty cover title is a deliberate override, not "follow"', () => {
  // The cover can leave a line out that Basic Information fills; an empty title falls to
  // the bare word, the same as a blank Basic Information title does.
  assert.equal(coverTitle({ 'heading.bundleTitle': 'Filled In', 'cover.bundleTitle': '' }), 'BUNDLE');
});

test('Court Ref/Claim No. and Prepared By follow Basic Information, or are overridden on the cover', async (t) => {
  if (!havePdftotext()) return skip('pdftotext is needed to read the rendered page');
  const base = { ...FULL, 'heading.claimNumber': 'BASIC-REF-1', 'heading.author': 'Basic Author' };
  const follows = coverText(await makeCoverPdf({ ...base, 'cover.claimNumber': null, 'cover.author': null }));
  assert.ok(follows.includes('BASIC-REF-1') && follows.includes('Basic Author'), `should follow: ${follows}`);
  const own = coverText(await makeCoverPdf({ ...base, 'cover.claimNumber': 'COVER-REF-9', 'cover.author': 'Cover Author' }));
  assert.ok(own.includes('COVER-REF-9') && own.includes('Cover Author'), `should use its own: ${own}`);
  assert.ok(!own.includes('BASIC-REF-1') && !own.includes('Basic Author'), 'Basic Information values must not leak through an override');
  const blank = coverText(await makeCoverPdf({ ...base, 'cover.author': '' }));
  assert.ok(!blank.includes('Prepared by'), 'an empty override leaves the Prepared by line off');
});
