/**
 * Encrypted and damaged input handling.
 *
 * Every fixture is generated by tests/fixtures.mjs, which checks that it
 * damaged the file in the way it claims, so an undamaged "damaged" fixture
 * cannot let these tests pass without testing anything.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as fx from './fixtures.mjs';
import {
  loadPdf, unlockPdf, looksEncrypted, countPagesMissingContent, declaredPageCount,
  EncryptedPdfError, UnreadablePdfError,
} from '../public/js/bundletoolPdfLoad.js';
import { validateAndCountPages } from '../public/js/bundletoolPages.js';

const clean = await fx.makePdf(7, 'CLEAN');

test('a clean PDF loads and reports no damage', async () => {
  const r = await loadPdf(clean);
  assert.equal(r.pageCount, 7);
  assert.equal(r.declaredPageCount, 7);
  assert.equal(r.damaged, false);
  assert.equal(r.disclosure, null);
});

test('an encrypted PDF is refused, never opened', async () => {
  const encrypted = await fx.makeEncryptedPdf(3);
  assert.equal(looksEncrypted(encrypted), true);
  await assert.rejects(() => loadPdf(encrypted), EncryptedPdfError);
});

test('the encryption refusal asks for the password, and never suggests print-to-PDF', async () => {
  // Printing the document to a new PDF to strip the encryption is advice a
  // legal tool has no business giving: the app asks for the password and
  // decrypts on the device instead.
  const encrypted = await fx.makeEncryptedPdf(2);
  const result = await validateAndCountPages(encrypted);
  assert.equal(result.errorKind, 'encrypted');
  assert.match(result.error, /password-protected/i);
  assert.match(result.error, /unlock/i);
  assert.ok(!/print/i.test(result.error), 'must not recommend the print-to-PDF workaround');
  assert.equal(result.pageCount, undefined, 'a refused file must not report a page count');
});

test('a file that is not a PDF is refused as unreadable, not as encrypted', async () => {
  const notPdf = new Uint8Array(Buffer.from('Dear Sirs, please find attached...'));
  await assert.rejects(() => loadPdf(notPdf), UnreadablePdfError);
  const result = await validateAndCountPages(notPdf);
  assert.equal(result.errorKind, 'unreadable');
});

test('pages that lost their content stream are detected and disclosed', async () => {
  // The page objects survive; the ink does not. pdf-lib reports these as
  // ordinary pages and raises nothing, which is exactly the silent failure
  // this detection exists for.
  const damaged = fx.damageContentStreams(clean, [5, 6, 7]);
  const r = await loadPdf(damaged);
  assert.equal(r.damaged, true);
  assert.equal(r.pageCount, 7);
  assert.equal(r.pagesMissingContent, 3);
  assert.match(r.disclosure, /Recovered 7 pages; the file is damaged and may be incomplete/);
  assert.match(r.disclosure, /3 of the recovered pages lost their content and will appear blank/);
});

test('pages missing from the tree are reported against the count the file claims', async () => {
  const damaged = fx.damagePageObjects(clean, [6, 7]);
  const r = await loadPdf(damaged);
  assert.equal(r.damaged, true);
  assert.equal(r.pageCount, 5);
  assert.equal(r.declaredPageCount, 7);
  assert.match(r.disclosure, /Recovered 5 pages/);
  assert.match(r.disclosure, /own page index records 7 pages/);
});

test('a denominator is never invented when the file does not supply one', async () => {
  // With the cross-reference table destroyed there is nothing left to count,
  // so the message must not imply otherwise.
  const damaged = fx.damageContentStreams(clean, [4]);
  const r = await loadPdf(damaged);
  assert.match(r.disclosure, /may be incomplete/);
  assert.doesNotMatch(r.disclosure, /\d+ of \d+ pages/,
    'must not claim "N of M" unless M was actually read from the file');
});

test('a corrupt cross-reference table alone is recovered silently', async () => {
  // pdf-lib ignores the xref and scans the objects, so nothing is lost and
  // there is nothing to disclose. Warning here would be noise, and noise
  // trains people to click through the warnings that matter.
  const r = await loadPdf(fx.corruptXrefOffset(clean));
  assert.equal(r.pageCount, 7);
  assert.equal(r.damaged, false);
});

test('a truncated file that cannot be parsed at all is refused', async () => {
  await assert.rejects(() => loadPdf(fx.truncate(clean, 0.7)), UnreadablePdfError);
});

test('validateAndCountPages surfaces damage rather than swallowing it', async () => {
  const result = await validateAndCountPages(fx.damageContentStreams(clean, [2]));
  assert.equal(result.damaged, true);
  assert.equal(result.pageCount, 7);
  assert.ok(result.disclosure);
});

test('the content-loss detector does not cry wolf on a healthy document', async () => {
  const { doc } = await loadPdf(clean);
  assert.equal(countPagesMissingContent(doc), 0);
  assert.equal(declaredPageCount(doc), 7);
});

// ── Passwords: unlock on the way in, protect on the way out ──────────────────

test('an owner-password-only PDF opens silently, like every ordinary viewer', async () => {
  // Court seals and "no editing" exports have a BLANK user password. Refusing
  // them would send people to print-to-PDF workarounds, which is worse than
  // opening them the way Acrobat does.
  const sealed = await fx.makeOwnerOnlyEncryptedPdf(2);
  const r = await loadPdf(sealed);
  assert.equal(r.pageCount, 2);
  assert.equal(r.damaged, false);
});

test('a real user password is still refused without the password', async () => {
  const encrypted = await fx.makeEncryptedPdf(3);
  await assert.rejects(() => loadPdf(encrypted), EncryptedPdfError);
});

test('unlockPdf with the right password yields an ordinary decrypted PDF', async () => {
  const encrypted = await fx.makeEncryptedPdf(3);
  const unlocked = await unlockPdf(encrypted, 'user-pw');
  // Behavioural claim, not a byte-level one: the re-save can retain a
  // vestigial /Encrypt trailer reference (the engine writes it even after
  // decryption), but the content is plaintext and the file loads with no
  // password, which is what "unlocked" has to mean.
  const r = await loadPdf(unlocked);
  assert.equal(r.pageCount, 3);
  assert.equal(r.damaged, false);
});

test('unlockPdf with the wrong password throws, and says so usefully', async () => {
  const encrypted = await fx.makeEncryptedPdf(1);
  await assert.rejects(() => unlockPdf(encrypted, 'nope'), (err) => {
    assert.equal(err.name, 'EncryptedPdfError');
    assert.match(err.userMessage, /did not open/);
    return true;
  });
});

test('encryptPdf protects a bundle so it needs its password to open', async () => {
  const bundle = await fx.makePdf(4, 'BUNDLE');
  const { encryptPdf } = await import('../public/js/bundletoolPages.js');
  const protectedBytes = await encryptPdf(bundle, 'hearing-2026');
  await assert.rejects(() => loadPdf(protectedBytes), EncryptedPdfError);
  const reopened = await loadPdf(await unlockPdf(protectedBytes, 'hearing-2026'));
  assert.equal(reopened.pageCount, 4);
});

// ── Images become documents ──────────────────────────────────────────────────

test('a PNG becomes a one-page A4 PDF', async () => {
  const { imageToPdf } = await import('../public/js/bundletoolPages.js');
  const pdfBytes = await imageToPdf(fx.makePng(40, 60));
  const r = await loadPdf(pdfBytes instanceof Uint8Array ? pdfBytes : new Uint8Array(pdfBytes));
  assert.equal(r.pageCount, 1);
  const { width, height } = r.doc.getPage(0).getSize();
  assert.ok(Math.abs(width - 595.28) < 0.1 && Math.abs(height - 841.89) < 0.1, 'the page must be A4, whatever the image size');
});

test('bytes that are not an image are refused by their content, not their name', async () => {
  const { imageToPdf } = await import('../public/js/bundletoolPages.js');
  await assert.rejects(() => imageToPdf(new Uint8Array([1, 2, 3, 4, 5, 6, 7, 8, 9])), /Not a JPG or PNG/);
});
