/**
 * End-to-end: merge, number, add metadata, then read the result back.
 *
 * This is the closest a Node test gets to the real thing. The index pages are
 * generated by jsPDF in the browser, which is not available here, so a
 * synthetic two-page "index" stands in for them; everything downstream of that
 * is the shipped code path.
 */
import { test, skip } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import * as fx from './fixtures.mjs';
import { PDFDocument, PDFName } from '../public/js/bundletoolPdfLib.js';
import { loadPdf } from '../public/js/bundletoolPdfLoad.js';
import { mergeFileEntries, mergeTwoPdfs } from '../public/js/bundletoolMerge.js';
import { applyPageNumbering } from '../public/js/bundletoolPages.js';
import { applyMeta, readBundleIndex } from '../public/js/bundletoolMeta.js';
import { openBundle, splitBundlePdf, coverSourceOf } from '../public/js/bundletoolRestore.js';
import { readOutline } from '../public/js/bundletoolOutline.js';
import { makeCoverPdf, resolveCoverSource } from '../public/js/bundletoolCover.js';

const CV_META = {
  'pageOptions.coversheet': true,
  'pageOptions.coverSource': 'uploaded',
  'pageOptions.printableBundle': false,
  'index.outlineItemStyle': 'plain',
  'index.fontFace': 'serif',
  'index.dateStyle': 'DD Mon. YYYY',
  'index.sectionPrefix': '',
  'heading.bundleTitle': 'Bundle for hearing on 14 March 2026',
  'heading.projectName': 'Re: X (A Child)',
  'heading.author': 'A. Solicitor',
  'heading.claimNumber': 'ZC00P00456',
  'pageNumbering.footerFont': 'courier',
  'pageNumbering.alignment': 'centre',
  'pageNumbering.numberingStyle': 'PageX',
  'pageNumbering.footerPrefix': '',
  'pageNumbering.pageNumberPerSection': false,
};

const CV_FOOTER = {
  'pageNumbering.footerPrefix': 'Bundle',
  'pageNumbering.alignment': 'centre',
  'pageNumbering.numberingStyle': 'PageX',
  // A font other than the default, so the footer is drawn in the font the
  // setting names. The harness serves public/ over fetch(), so these tests
  // exercise the font file the product actually draws with.
  'pageNumbering.footerFont': 'courier',
  'pageNumbering.footerFontSize': 'small',
  'pageNumbering.pageNumberColour': 'black',
  'pageNumbering.pageNumberPerSection': false,
};

/** The cover-page case details a generated cover is drawn from. Invented. */
const CV_COVER = {
  'cover.courtName': 'IN THE FAMILY COURT AT CENTRAL LONDON',
  'cover.applicantName': 'MS A SAMPLE',
  'cover.respondentName': 'MR B EXAMPLE',
};

/**
 * Builds a bundle the way bundletoolMain.js does, minus the jsPDF index.
 *
 * `cover` is 'uploaded' (a supplied first page) or 'generated' (the cover this
 * app draws). Either way it is physical page 1 and the index is
 * page 2, which is the property every offset in the pipeline depends on.
 */
async function buildBundle({ cover = 'uploaded' } = {}) {
  const docs = [
    { filename: 'application.pdf', buffer: await fx.makePdf(3, 'APPLICATION') },
    { filename: 'statement.pdf', buffer: await fx.makePdf(4, 'STATEMENT') },
    { filename: 'order.pdf', buffer: await fx.makePdf(2, 'ORDER') },
  ];

  const merged = await mergeFileEntries(docs, false);       // [7]  documents
  const index = await fx.makePdf(2, 'INDEX');               // stands in for jsPDF
  const withIndex = await mergeTwoPdfs(index, merged);      // [8]  index first
  const coversheet = cover === 'generated'
    ? await makeCoverPdf({ ...CV_META, ...CV_COVER })
    : await fx.makePdf(1, 'COVERSHEET');
  const withCover = await mergeTwoPdfs(coversheet, withIndex); // [9] cover first

  // Cover is page 1, so the index is page 2 -> index 1.
  const INDEX_PAGE_INDEX = 1;
  const numbered = await applyPageNumbering(withCover, CV_FOOTER, [], INDEX_PAGE_INDEX);

  const tocEntries = [{
    sectionID: '0001', sectionNumber: 1, sectionLabel: 'A', sectionTitle: 'Documents',
    beginsOnPdfPage: 4, actualPdfStartPageWithToc: 4,
    entries: [
      { tabNumber: 1, title: 'Application', date: '2026-01-05', filename: 'application.pdf', pageCount: 3, beginsOnPdfPage: 4, beginsOnPageOfSection: 1, actualPdfStartPageWithToc: 4 },
      { tabNumber: 2, title: 'Statement', date: '2026-02-11', filename: 'statement.pdf', pageCount: 4, beginsOnPdfPage: 7, beginsOnPageOfSection: 4, actualPdfStartPageWithToc: 7 },
      { tabNumber: 3, title: 'Order', date: '2026-03-02', filename: 'order.pdf', pageCount: 2, beginsOnPdfPage: 11, beginsOnPageOfSection: 8, actualPdfStartPageWithToc: 11 },
    ],
  }];

  const rows = tocEntries[0].entries.map((e, i) => ({
    pageNumber: 1, tabNumber: e.tabNumber, x: 20, y: 40 + i * 10, width: 170, height: 8,
  }));

  const cv = cover === 'generated'
    ? { ...CV_META, ...CV_COVER, 'pageOptions.coverSource': 'generated' }
    : CV_META;
  const final = await applyMeta(numbered, rows, tocEntries, cv);
  return { final, tocEntries, INDEX_PAGE_INDEX };
}

test('a bundle builds end to end with the expected page count', async () => {
  const { final } = await buildBundle();
  const { doc } = await loadPdf(final);
  // 1 coversheet + 2 index + 3 + 4 + 2 documents
  assert.equal(doc.getPageCount(), 12);
});

test('every page carries a footer linking to the index, not to the coversheet', async () => {
  const { final, INDEX_PAGE_INDEX } = await buildBundle();
  const { doc } = await loadPdf(final);
  const indexRef = doc.getPage(INDEX_PAGE_INDEX).ref;

  let footerLinks = 0;
  for (const page of doc.getPages()) {
    const annots = doc.context.lookup(page.node.get(PDFName.of('Annots')));
    assert.ok(annots, 'page has no annotations at all');
    for (let i = 0; i < annots.size(); i++) {
      const annot = doc.context.lookup(annots.get(i));
      const dest = doc.context.lookup(annot.get(PDFName.of('Dest')));
      if (dest?.get(0)?.tag === indexRef.tag) footerLinks++;
    }
  }
  assert.ok(footerLinks >= doc.getPageCount(),
    `expected at least one index link per page, found ${footerLinks} across ${doc.getPageCount()} pages`);
  assert.notEqual(INDEX_PAGE_INDEX, 0, 'this bundle has a coversheet, so the index is not page 1');
});

test('the finished bundle carries a nested outline', async () => {
  const { final } = await buildBundle();
  const { doc } = await loadPdf(final);
  const outline = readOutline(doc);
  assert.equal(outline[0].title, '[0] Index');
  assert.equal(outline[0].pageIndex, 1, 'the Index bookmark must point at the index page');
  assert.equal(outline[1].title, 'A: Documents');
  assert.equal(outline[1].children.length, 3);
});

test('the bundle reopens and splits back into its documents', async () => {
  const { final } = await buildBundle();
  const opened = await openBundle(final);

  assert.equal(opened.version, 3);
  assert.equal(opened.config.heading.claimNumber, 'ZC00P00456');
  assert.equal(opened.config.pageOptions.coversheet, true);

  const files = await splitBundlePdf(opened.doc, opened.metadata, true);
  assert.deepEqual(
    [...files.keys()].sort(),
    ['application.pdf', 'coversheet.pdf', 'order.pdf', 'statement.pdf'],
  );

  const statement = await PDFDocument.load(files.get('statement.pdf'));
  assert.equal(statement.getPageCount(), 4);
});

test('splitting a bundle reports progress once per document, with a rising index and a fixed total', async () => {
  const { final } = await buildBundle();
  const opened = await openBundle(final);

  const calls = [];
  await splitBundlePdf(opened.doc, opened.metadata, true, (i, total) => calls.push([i, total]));

  // buildBundle's fixture has three documents (the coversheet is handled
  // separately, outside this per-document loop, so it does not report).
  assert.equal(calls.length, 3);
  assert.deepEqual(calls.map(([i]) => i), [1, 2, 3]);
  for (const [, total] of calls) assert.equal(total, 3);
});

test('documents come back out without the bundle footers on them', async () => {
  const { final } = await buildBundle();
  const opened = await openBundle(final);
  const files = await splitBundlePdf(opened.doc, opened.metadata, true);

  for (const [name, bytes] of files) {
    const doc = await PDFDocument.load(bytes);
    for (const page of doc.getPages()) {
      const contents = doc.context.lookup(page.node.get(PDFName.of('Contents')));
      const size = contents?.size ? contents.size() : 0;
      for (let i = 0; i < size; i++) {
        const s = doc.context.lookup(contents.get(i));
        assert.equal(s?.dict?.get(PDFName.of('BundleToolFooter')), undefined,
          `${name} still carries a bundle footer`);
      }
    }
  }
});

test('a rebuilt bundle round-trips a second time', async () => {
  // Re-bundling is the case that stacks footers and duplicates metadata, so it
  // gets exercised rather than assumed.
  const { final } = await buildBundle();
  const opened = await openBundle(final);
  const files = await splitBundlePdf(opened.doc, opened.metadata, true);

  const entries = ['application.pdf', 'statement.pdf', 'order.pdf']
    .map((f) => ({ filename: f, buffer: files.get(f) }));
  const remerged = await mergeFileEntries(entries, false);
  const { doc } = await loadPdf(remerged);
  assert.equal(doc.getPageCount(), 9, '3 + 4 + 2 pages, with no blanks introduced');
});

test('printable mode pads odd-length documents to an even page count', async () => {
  const docs = [
    { filename: 'a.pdf', buffer: await fx.makePdf(3, 'A') },
    { filename: 'b.pdf', buffer: await fx.makePdf(2, 'B') },
    { filename: 'c.pdf', buffer: await fx.makePdf(1, 'C') },
  ];
  const merged = await mergeFileEntries(docs, true);
  const { doc } = await loadPdf(merged);
  assert.equal(doc.getPageCount(), 4 + 2 + 2);
});

test('page rotation survives merging', async () => {
  const rotated = await fx.makePdf(4, 'ROT', { rotations: [0, 90, 180, 270] });
  const merged = await mergeFileEntries([{ filename: 'r.pdf', buffer: rotated }], false);
  const { doc } = await loadPdf(merged);
  assert.deepEqual(doc.getPages().map((p) => p.getRotation().angle), [0, 90, 180, 270]);
});

// ── Where numbering starts ───────────────────────────────────────────────────

function havePdftotext() {
  try {
    execFileSync('pdftotext', ['-v'], { stdio: 'ignore' });
    return true;
  } catch { return false; }
}

/** The text of one page of a PDF, as a reader would search it. */
function pageText(bytes, page) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'bundletool-text-'));
  try {
    const file = path.join(dir, 'b.pdf');
    fs.writeFileSync(file, bytes);
    return execFileSync('pdftotext', ['-f', String(page), '-l', String(page), file, '-'],
      { encoding: 'utf8' }).replace(/\s+/g, ' ').trim();
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

test('numbering starts at the coversheet: it is page 1 and the index is page 2', async (t) => {
  if (!havePdftotext()) return skip('pdftotext is needed to read the rendered labels');

  const { final, INDEX_PAGE_INDEX } = await buildBundle();

  // The whole point: the coversheet is numbered, not skipped, so the count runs
  // continuously from the very first sheet of the bundle.
  assert.match(pageText(final, 1), /COVERSHEET page 1 .*Bundle Page 1$/,
    'the coversheet must carry "Bundle Page 1"');
  assert.match(pageText(final, 2), /INDEX page 1 .*Bundle Page 2$/,
    'the index must be page 2 when there is a coversheet');
  assert.match(pageText(final, 4), /APPLICATION page 1 .*Bundle Page 4$/);

  // ...and the footer still links to the index rather than to the coversheet.
  assert.equal(INDEX_PAGE_INDEX, 1);
});

test('without a coversheet the index is page 1 and nothing shifts', async (t) => {
  if (!havePdftotext()) return skip('pdftotext is needed to read the rendered labels');

  const merged = await mergeFileEntries(
    [{ filename: 'application.pdf', buffer: await fx.makePdf(3, 'APPLICATION') }], false,
  );
  const withIndex = await mergeTwoPdfs(await fx.makePdf(2, 'INDEX'), merged);
  const numbered = await applyPageNumbering(withIndex, CV_FOOTER, [], 0);

  assert.match(pageText(numbered, 1), /INDEX page 1 .*Bundle Page 1$/);
  assert.match(pageText(numbered, 3), /APPLICATION page 1 .*Bundle Page 3$/);
});

test('the stored bundle index records pages counting the coversheet', async () => {
  // If the embedded payload counted from the index instead, every recorded page
  // would be one lower than the footer printed, and a reloaded bundle would
  // rebuild with the documents one page out.
  const { final } = await buildBundle();
  const { doc } = await loadPdf(final);
  const payload = readBundleIndex(doc);
  assert.equal(payload.config.pageOptions.coversheet, true);
  assert.deepEqual(payload.sections[0].files.map((f) => f.page), [4, 7, 11],
    'recorded pages must be the physical bundle pages, coversheet included');
});

// ── The generated cover page ─────────────────────────────────────────────────

test('an uploaded coversheet wins over the generated cover', () => {
  // The failure this rules out is two cover pages. There is exactly one rule
  // and it lives in one function.
  assert.equal(resolveCoverSource({ hasUploadedCover: true, generateCover: true }), 'uploaded');
  assert.equal(resolveCoverSource({ hasUploadedCover: true, generateCover: false }), 'uploaded');
  assert.equal(resolveCoverSource({ hasUploadedCover: false, generateCover: true }), 'generated');
  assert.equal(resolveCoverSource({ hasUploadedCover: false, generateCover: false }), 'none');
  // Absent means none: covers are opt-in through the coversheet maker, so
  // only an explicit true generates one.
  assert.equal(resolveCoverSource({ hasUploadedCover: false, generateCover: undefined }), 'none');
});

test('a bundle that records pageOptions.coversheet but no coverSource reads as having an uploaded cover', () => {
  assert.equal(coverSourceOf({ pageOptions: { coversheet: true } }), 'uploaded');
  assert.equal(coverSourceOf({ pageOptions: { coversheet: false } }), 'none');
  assert.equal(coverSourceOf({ pageOptions: { coversheet: true, coverSource: 'generated' } }), 'generated');
  assert.equal(coverSourceOf({}), 'none');
  assert.equal(coverSourceOf(null), 'none');
  // Junk in the stored value is not trusted into the switch.
  assert.equal(coverSourceOf({ pageOptions: { coversheet: true, coverSource: 'nonsense' } }), 'uploaded');
});

test('a generated cover slots into the same place an uploaded one does', async () => {
  const { final } = await buildBundle({ cover: 'generated' });
  const { doc } = await loadPdf(final);
  // 1 cover + 2 index + 3 + 4 + 2 documents: the same 12 as the uploaded case.
  assert.equal(doc.getPageCount(), 12);
});

test('the generated cover is bundle page 1 and the index is page 2', async (t) => {
  if (!havePdftotext()) return skip('pdftotext is needed to read the rendered labels');
  const { final } = await buildBundle({ cover: 'generated' });

  const page1 = pageText(final, 1);
  assert.ok(page1.includes('BUNDLE FOR HEARING ON 14 MARCH 2026'),
    `page 1 should be the generated cover, got: ${page1}`);
  // Not anchored to the end of the string: "Prepared by" sits bottom right,
  // beside the footer, and pdftotext's physical-layout reading order between
  // two bottom-of-page items depends on the footer's own alignment setting,
  // not on which was drawn first. What matters is that the footer is there.
  assert.ok(page1.includes('Bundle Page 1'), 'the generated cover carries the bundle\'s own page 1 footer');
  assert.match(pageText(final, 2), /INDEX page 1 .*Bundle Page 2$/);
  assert.match(pageText(final, 4), /APPLICATION page 1 .*Bundle Page 4$/);
});

test('the footer on a generated cover links to the index, not to itself', async () => {
  const { final, INDEX_PAGE_INDEX } = await buildBundle({ cover: 'generated' });
  const { doc } = await loadPdf(final);
  const indexRef = doc.getPage(INDEX_PAGE_INDEX).ref;
  const annots = doc.context.lookup(doc.getPage(0).node.get(PDFName.of('Annots')));
  assert.ok(annots, 'the cover has no annotations at all');
  let toIndex = 0;
  for (let i = 0; i < annots.size(); i++) {
    const dest = doc.context.lookup(doc.context.lookup(annots.get(i)).get(PDFName.of('Dest')));
    if (dest?.get(0)?.tag === indexRef.tag) toIndex++;
  }
  assert.ok(toIndex >= 1);
});

test('the stored index counts the generated cover in its page numbers', async () => {
  const { final } = await buildBundle({ cover: 'generated' });
  const { doc } = await loadPdf(final);
  const payload = readBundleIndex(doc);
  assert.equal(payload.config.pageOptions.coversheet, true);
  assert.equal(payload.config.pageOptions.coverSource, 'generated');
  assert.deepEqual(payload.sections[0].files.map((f) => f.page), [4, 7, 11],
    'a generated cover offsets the recorded pages exactly as an uploaded one does');
});

test('the cover details are stored so a reopened bundle can redraw the cover', async () => {
  const { final } = await buildBundle({ cover: 'generated' });
  const { doc } = await loadPdf(final);
  const payload = readBundleIndex(doc);
  assert.deepEqual(payload.config.cover, {
    courtName: 'IN THE FAMILY COURT AT CENTRAL LONDON',
    matterOf: '',
    applicantName: 'MS A SAMPLE',
    respondentName: 'MR B EXAMPLE',
    partyLabel1: '',
    partyLabel2: '',
    extraText: '',
    claimNumber: null,
    bundleTitle: null,
    author: null,
  });
});

test('reopening a bundle with a generated cover does not hand it back as a file', async () => {
  // A generated cover is redrawn from the stored fields, not reused. Bringing
  // it back as an uploaded coversheet would freeze last time's hearing date
  // onto the front of the rebuilt bundle, and it would then win over the
  // regenerated one: silently, because it looks like a cover either way.
  const { final } = await buildBundle({ cover: 'generated' });
  const opened = await openBundle(final);
  assert.equal(coverSourceOf(opened.config), 'generated');

  const files = await splitBundlePdf(opened.doc, opened.metadata, coverSourceOf(opened.config) === 'uploaded');
  assert.deepEqual([...files.keys()].sort(), ['application.pdf', 'order.pdf', 'statement.pdf']);

  // The documents themselves still come back whole and unnumbered.
  const statement = await PDFDocument.load(files.get('statement.pdf'));
  assert.equal(statement.getPageCount(), 4);
  for (const page of statement.getPages()) {
    const contents = doc0Contents(statement, page);
    for (const s of contents) {
      assert.equal(s?.dict?.get(PDFName.of('BundleToolFooter')), undefined);
    }
  }
});

/** Every content stream of one page, as objects. */
function doc0Contents(doc, page) {
  const contents = doc.context.lookup(page.node.get(PDFName.of('Contents')));
  const size = contents?.size ? contents.size() : 0;
  return Array.from({ length: size }, (_, i) => doc.context.lookup(contents.get(i)));
}

test('an uploaded coversheet comes back as a file', async () => {
  // The other half of the rule above: nothing about generated covers may change
  // what happens to a coversheet the user supplied.
  const { final } = await buildBundle({ cover: 'uploaded' });
  const opened = await openBundle(final);
  assert.equal(coverSourceOf(opened.config), 'uploaded');
  const files = await splitBundlePdf(opened.doc, opened.metadata, true);
  assert.ok(files.has('coversheet.pdf'));
});

test('the bundle index survives the whole pipeline intact', async () => {
  const { final, tocEntries } = await buildBundle();
  const { doc } = await loadPdf(final);
  const payload = readBundleIndex(doc);
  assert.equal(payload.sections[0].files.length, 3);
  assert.deepEqual(
    payload.sections[0].files.map((f) => f.filename),
    tocEntries[0].entries.map((e) => e.filename),
  );
  assert.deepEqual(payload.sections[0].files.map((f) => f.page), [4, 7, 11]);
});

test('a bundle that never recorded a cover setting reopens with no cover', () => {
  // Covers are opt-in through the coversheet maker, so an unrecorded setting
  // means none in both directions: nothing is stripped from page 1 on the way
  // in, and no cover is regenerated on the way out. The generate-time warning
  // catches a reopened bundle heading out with no cover at all.
  assert.equal(coverSourceOf({}), 'none');
  assert.equal(coverSourceOf({ pageOptions: {} }), 'none');
  assert.equal(coverSourceOf(undefined), 'none');
});
